# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f89a12917f3f47a362452a53bad48ab663d16ccdf7fc8b340345f87428cc982c08383c5f03640bbc655ae548a1134fa96839e010a65a45cb9eb5fdf70355ad9

test:
  secret_key_base: 4d71bc939cfefb561dc5ffd48a488388f9ddddbd60ec78d2122a77f9ac3f7e169a617ec4c15a9b4ac4219cc690a35fbbe1a4dfc3c8644a18fe70c2d517dcd481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
